# Site settings
title: Nkululeko Thangelane
description: Nkululeko Thangelane, Personal Blog.
cover: assets/images/radhakrishna.jpg
logo: assets/images/logos.png
favicon: assets/images/favicon.png
baseurl: "/nkululekothangelane.github.io/" # the subpath of your site, e.g. /blog/ or / for root
url: "https://nkululekothangelane.github.io/" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage

# Social
facebook: facebook
twitter: twitter
github:  github
linkedin: linkedin

#Additional Pages
about: about
contact: contact
privacy-policy: privacy-policy


permalink: /:title


# Google Analytics
analytics_id: ""

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

plugins:
  - jekyll-paginate


# Settings for rake task
safe: False
lsi: False
username: nkululekothangelane #github username
repo: nkululekothangelane.github.io #github repository
branch: master #branch
relative_source: ../nkululekothangelane.github.io/ #source directory
destination: ../nkululekothangelane.github.io/ #destination directory
production_url:  https://samanyougarg.com/
source_url:  https://github.com/NkululekoThangelane/nkululekothangelane.github.io/ #source repository url

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
